# -*- coding: utf-8 -*-
"""Sum of Multiple elements.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vck1vNUPglLGZ2MxRjUlPD7j8v1DVGfP
"""

x = input("Enter Values")
y = x.split()
sum = 0
for i in y:
    sum = sum + int(i)
print("The Sum of Entered",sum)